# Generated by Django 4.2.16 on 2024-12-09 11:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("subtitle", models.CharField(max_length=200)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("tech", "테크/가전"),
                            ("fashion", "패션"),
                            ("design", "디자인"),
                            ("art", "예술"),
                            ("food", "푸드"),
                            ("publishing", "출판"),
                            ("music", "음악"),
                            ("film", "영화/비디오"),
                        ],
                        max_length=20,
                    ),
                ),
                ("target_amount", models.DecimalField(decimal_places=2, max_digits=15)),
                (
                    "current_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                ("start_date", models.DateTimeField()),
                ("end_date", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "작성중"),
                            ("pending", "심사중"),
                            ("active", "진행중"),
                            ("successful", "성공"),
                            ("failed", "실패"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("description", models.TextField()),
                ("risks", models.TextField()),
                ("thumbnail", models.ImageField(upload_to="projects/thumbnails/")),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Reward",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("amount", models.DecimalField(decimal_places=2, max_digits=15)),
                ("stock", models.IntegerField(default=-1)),
                ("delivery_date", models.DateField()),
                (
                    "shipping_fee",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rewards",
                        to="projects.project",
                    ),
                ),
            ],
        ),
    ]
