# Generated by Django 4.2.16 on 2024-12-09 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="balance",
            field=models.IntegerField(default=100000),
        ),
    ]
